language: python
python:
  - "2.7"
  - "3.6"
install:
- pip install -r requirements-dev.txt
script:
  - pytest
  - py.test --cov-report term-missing --cov=myPackage tests/
#  - py.test --cov-report html --cov=myPackage tests/
after_success:
  - coveralls