language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install -e . --use-mirrors
before_script:
  - pip install -r requirements-dev.txt --use-mirrors
  - pytest
  - py.test --cov=myPackage tests/
  - cd -
script:
  - py.test coveralls/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_success:
  - coveralls